# Generated by Django 2.2.10 on 2021-12-30 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choise',
            new_name='Choice',
        ),
    ]
